# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelwithcsv',
            name='csv_field',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
